
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8759/eureka
server:
  port: 8767
spring:
  application:
    name: config-client
feign:
  hystrix:
    enabled: true # 开启Feign的熔断功能
logging:
  level:
    com.leyou: debug
management:
  endpoints:
    web:
      exposure:
        #exclude: shutdown,threaddump   #此处控制的是不开放哪些端点
        include: "*" #此处控制的是开放哪些端点，如果需要开启少数端点可以这样配置：health,info。如果开启多个则使用*号开启除了exclude的端点
