
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8758/eureka,http://peer2:8759/eureka

server:
  port: 8762
spring:
  application:
    name: service-hi
  rabbitmq:
    host: 127.0.0.1
    # rabbitmq服务器连接端口 （默认为5672）
    port: 5672
    username: admin
    password: 123456

